THEMES = {
    "Slate": {
        "bg":           "#F0F2F5",
        "topbar":       "#FFFFFF",
        "panel":        "#FFFFFF",
        "panel_alt":    "#E8EBF0",
        "accent":       "#2563EB",
        "accent_dim":   "#1D4ED8",
        "accent_hover": "#3B82F6",
        "text":         "#111827",
        "text_muted":   "#6B7280",
        "text_dim":     "#9CA3AF",
        "success":      "#059669",
        "warning":      "#D97706",
        "error":        "#DC2626",
        "border":       "#E5E7EB",
        "progress_bg":  "#DBEAFE",
        "progress_fg":  "#2563EB",
        "btn_text":     "#FFFFFF",
        "tag_bg":       "#EFF6FF",
        "tag_text":     "#1D4ED8",
    },
    "Rose": {
        "bg":           "#FFF5F5",
        "topbar":       "#FFFFFF",
        "panel":        "#FFFFFF",
        "panel_alt":    "#FEE2E2",
        "accent":       "#E11D48",
        "accent_dim":   "#BE123C",
        "accent_hover": "#F43F5E",
        "text":         "#1C1917",
        "text_muted":   "#78716C",
        "text_dim":     "#A8A29E",
        "success":      "#059669",
        "warning":      "#D97706",
        "error":        "#DC2626",
        "border":       "#FCE7F3",
        "progress_bg":  "#FFE4E6",
        "progress_fg":  "#E11D48",
        "btn_text":     "#FFFFFF",
        "tag_bg":       "#FFF1F2",
        "tag_text":     "#BE123C",
    },
    "Forest": {
        "bg":           "#F0FDF4",
        "topbar":       "#FFFFFF",
        "panel":        "#FFFFFF",
        "panel_alt":    "#DCFCE7",
        "accent":       "#16A34A",
        "accent_dim":   "#15803D",
        "accent_hover": "#22C55E",
        "text":         "#14532D",
        "text_muted":   "#6B7280",
        "text_dim":     "#9CA3AF",
        "success":      "#16A34A",
        "warning":      "#D97706",
        "error":        "#DC2626",
        "border":       "#D1FAE5",
        "progress_bg":  "#D1FAE5",
        "progress_fg":  "#16A34A",
        "btn_text":     "#FFFFFF",
        "tag_bg":       "#ECFDF5",
        "tag_text":     "#15803D",
    },
    "Dark": {
        "bg":           "#0F172A",
        "topbar":       "#1E293B",
        "panel":        "#1E293B",
        "panel_alt":    "#0F172A",
        "accent":       "#38BDF8",
        "accent_dim":   "#0284C7",
        "accent_hover": "#7DD3FC",
        "text":         "#F1F5F9",
        "text_muted":   "#94A3B8",
        "text_dim":     "#475569",
        "success":      "#34D399",
        "warning":      "#FBBF24",
        "error":        "#F87171",
        "border":       "#334155",
        "progress_bg":  "#0C4A6E",
        "progress_fg":  "#38BDF8",
        "btn_text":     "#0F172A",
        "tag_bg":       "#0C4A6E",
        "tag_text":     "#7DD3FC",
    },
}

DEFAULT_THEME = "Slate"
