[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "devnotes"
version = "1.0.0"
description = "A fast, git-aware, taggable notes CLI for developers."
requires-python = ">=3.9"
dependencies = [
    "click>=8.0",
    "rich>=13.0",
]

[project.optional-dependencies]
gui = ["Pygments>=2.15"]

[project.scripts]
devnotes = "devnotes.cli:main"
devnotes-gui = "devnotes.gui:main"

[tool.setuptools]
packages = ["devnotes"]
